### ISSUE TITLE
Support for BuBeiDanCi

### ISSUE THREAD

**Issue by Hao7un** [bulletproof-system/zotero-maimemo-sync#17]
Hi! thank you for your great work! 

I am wondering whether this repo will support synchronizing zotero and BuBeiDanCi in the future? It would be a great help!

**Comment by bulletproof-system** [comment]
@Hao7un [v0.1.3](https://github.com/bulletproof-system/zotero-maimemo-sync/releases/tag/v0.1.3) is now available. You can use the `Export` feature to export your highlights to a text file, which can then be imported into the app via their [website](https://bbdc.cn/lexis_book_index).
